/**
 * SmMed
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

#include <QJsonArray>
#include <QJsonDocument>
#include <QJsonObject>
#include <QVariantMap>
#include <QDebug>

#include "Helpers.h"
#include "DocterApiRequest.h"

namespace HttpServer {

DocterApiRequest::DocterApiRequest(QHttpEngine::Socket *s, QSharedPointer<DocterApiHandler> hdl) : QObject(s), socket(s), handler(hdl) {
    auto headers = s->headers();
    for(auto itr = headers.begin(); itr != headers.end(); itr++) {
        requestHeaders.insert(QString(itr.key()), QString(itr.value()));
    }
}

DocterApiRequest::~DocterApiRequest(){
    disconnect(this, nullptr, nullptr, nullptr);
    qDebug() << "DocterApiRequest::~DocterApiRequest()";
}

QMap<QString, QString>
DocterApiRequest::getRequestHeaders() const {
    return requestHeaders;
}

void DocterApiRequest::setResponseHeaders(const QMultiMap<QString, QString>& headers){
    for(auto itr = headers.begin(); itr != headers.end(); ++itr) {
        responseHeaders.insert(itr.key(), itr.value());
    }
}


QHttpEngine::Socket* DocterApiRequest::getRawSocket(){
    return socket;
}


void DocterApiRequest::doctorGetRequest(){
    qDebug() << "/doctor";
    connect(this, &DocterApiRequest::doctorGet, handler.data(), &DocterApiHandler::doctorGet);

    
    qint32 office;
    if(socket->queryString().keys().contains("office")){
        fromStringValue(socket->queryString().value("office"), office);
    }
    


    emit doctorGet(office);
}


void DocterApiRequest::doctorIdGetRequest(const QString& idstr){
    qDebug() << "/doctor/{id}";
    connect(this, &DocterApiRequest::doctorIdGet, handler.data(), &DocterApiHandler::doctorIdGet);

    
    QString id;
    fromStringValue(idstr, id);
    

    emit doctorIdGet(id);
}


void DocterApiRequest::doctorPostRequest(){
    qDebug() << "/doctor";
    connect(this, &DocterApiRequest::doctorPost, handler.data(), &DocterApiHandler::doctorPost);

    
 
    
    QJsonDocument doc;
    socket->readJson(doc);
    QJsonObject obj = doc.object();
    Inline_object_3 inline_object_3;
    ::HttpServer::fromJsonValue(inline_object_3, obj);
    

    emit doctorPost(inline_object_3);
}


void DocterApiRequest::doctorPutRequest(){
    qDebug() << "/doctor";
    connect(this, &DocterApiRequest::doctorPut, handler.data(), &DocterApiHandler::doctorPut);

    
 
    
    QJsonDocument doc;
    socket->readJson(doc);
    QJsonObject obj = doc.object();
    Inline_object_2 inline_object_2;
    ::HttpServer::fromJsonValue(inline_object_2, obj);
    

    emit doctorPut(inline_object_2);
}



void DocterApiRequest::doctorGetResponse(const Inline_response_200_7& res){
    writeResponseHeaders();
    QJsonDocument resDoc(::HttpServer::toJsonValue(res).toObject());
    socket->writeJson(resDoc);
    if(socket->isOpen()){
        socket->close();
    }
}

void DocterApiRequest::doctorIdGetResponse(const Inline_response_200_1& res){
    writeResponseHeaders();
    QJsonDocument resDoc(::HttpServer::toJsonValue(res).toObject());
    socket->writeJson(resDoc);
    if(socket->isOpen()){
        socket->close();
    }
}

void DocterApiRequest::doctorPostResponse(const Inline_response_200_8& res){
    writeResponseHeaders();
    QJsonDocument resDoc(::HttpServer::toJsonValue(res).toObject());
    socket->writeJson(resDoc);
    if(socket->isOpen()){
        socket->close();
    }
}

void DocterApiRequest::doctorPutResponse(const Inline_response_200_5& res){
    writeResponseHeaders();
    QJsonDocument resDoc(::HttpServer::toJsonValue(res).toObject());
    socket->writeJson(resDoc);
    if(socket->isOpen()){
        socket->close();
    }
}


void DocterApiRequest::doctorGetError(const Inline_response_200_7& res, QNetworkReply::NetworkError error_type, QString& error_str){
    Q_UNUSED(error_type); // TODO: Remap error_type to QHttpEngine::Socket errors
    writeResponseHeaders();
    Q_UNUSED(error_str);  // response will be used instead of error string
    QJsonDocument resDoc(::HttpServer::toJsonValue(res).toObject());
    socket->writeJson(resDoc);
    if(socket->isOpen()){
        socket->close();
    }
}

void DocterApiRequest::doctorIdGetError(const Inline_response_200_1& res, QNetworkReply::NetworkError error_type, QString& error_str){
    Q_UNUSED(error_type); // TODO: Remap error_type to QHttpEngine::Socket errors
    writeResponseHeaders();
    Q_UNUSED(error_str);  // response will be used instead of error string
    QJsonDocument resDoc(::HttpServer::toJsonValue(res).toObject());
    socket->writeJson(resDoc);
    if(socket->isOpen()){
        socket->close();
    }
}

void DocterApiRequest::doctorPostError(const Inline_response_200_8& res, QNetworkReply::NetworkError error_type, QString& error_str){
    Q_UNUSED(error_type); // TODO: Remap error_type to QHttpEngine::Socket errors
    writeResponseHeaders();
    Q_UNUSED(error_str);  // response will be used instead of error string
    QJsonDocument resDoc(::HttpServer::toJsonValue(res).toObject());
    socket->writeJson(resDoc);
    if(socket->isOpen()){
        socket->close();
    }
}

void DocterApiRequest::doctorPutError(const Inline_response_200_5& res, QNetworkReply::NetworkError error_type, QString& error_str){
    Q_UNUSED(error_type); // TODO: Remap error_type to QHttpEngine::Socket errors
    writeResponseHeaders();
    Q_UNUSED(error_str);  // response will be used instead of error string
    QJsonDocument resDoc(::HttpServer::toJsonValue(res).toObject());
    socket->writeJson(resDoc);
    if(socket->isOpen()){
        socket->close();
    }
}


void DocterApiRequest::sendCustomResponse(QByteArray & res, QNetworkReply::NetworkError error_type){
    Q_UNUSED(error_type); // TODO
    socket->write(res);
    if(socket->isOpen()){
        socket->close();
    }    
}

void DocterApiRequest::sendCustomResponse(QIODevice *res, QNetworkReply::NetworkError error_type){
    Q_UNUSED(error_type);  // TODO
    socket->write(res->readAll());
    if(socket->isOpen()){
        socket->close();
    }
}

}
