/**
 * SmMed
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

#ifndef _UserApiRequest_H
#define _UserApiRequest_H

#include <QObject>
#include <QStringList>
#include <QMultiMap>
#include <QNetworkReply>
#include <QSharedPointer>

#include <qhttpengine/socket.h>
#include "Inline_object.h"
#include "Inline_object_1.h"
#include "Inline_response_200_3.h"
#include "Inline_response_200_5.h"
#include "Inline_response_200_6.h"
#include <QString>
#include "UserApiHandler.h"

namespace HttpServer {

class UserApiRequest : public QObject
{
    Q_OBJECT

public:
    UserApiRequest(QHttpEngine::Socket *s, QSharedPointer<UserApiHandler> handler);
    virtual ~UserApiRequest();

    void userIdGetRequest(const QString& id);
    void userPostRequest();
    void userPutRequest();
    

    void userIdGetResponse(const Inline_response_200_3& res);
    void userPostResponse(const Inline_response_200_6& res);
    void userPutResponse(const Inline_response_200_5& res);
    

    void userIdGetError(const Inline_response_200_3& res, QNetworkReply::NetworkError error_type, QString& error_str);
    void userPostError(const Inline_response_200_6& res, QNetworkReply::NetworkError error_type, QString& error_str);
    void userPutError(const Inline_response_200_5& res, QNetworkReply::NetworkError error_type, QString& error_str);
    

    void sendCustomResponse(QByteArray & res, QNetworkReply::NetworkError error_type);

    void sendCustomResponse(QIODevice *res, QNetworkReply::NetworkError error_type);

    QMap<QString, QString> getRequestHeaders() const;

    QHttpEngine::Socket* getRawSocket();

    void setResponseHeaders(const QMultiMap<QString,QString>& headers);

signals:
    void userIdGet(QString id);
    void userPost(Inline_object_1 inline_object_1);
    void userPut(Inline_object inline_object);
    

private:
    QMap<QString, QString> requestHeaders;
    QMap<QString, QString> responseHeaders;
    QHttpEngine::Socket  *socket;
    QSharedPointer<UserApiHandler> handler;

    inline void writeResponseHeaders(){
        QHttpEngine::Socket::HeaderMap resHeaders;
        for(auto itr = responseHeaders.begin(); itr != responseHeaders.end(); ++itr) {
            resHeaders.insert(itr.key().toUtf8(), itr.value().toUtf8());
        }
        socket->setHeaders(resHeaders);
        socket->writeHeaders();
    }
};

}

#endif // _UserApiRequest_H
