/**
 * SmMed
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * User.h
 *
 * 
 */

#ifndef User_H
#define User_H

#include <QJsonObject>

#include <QString>

#include "Enum.h"
#include "Object.h"

namespace HttpServer {

class User : public Object {
public:
    User();
    User(QString json);
    ~User() override;

    QString asJson() const override;
    QJsonObject asJsonObject() const override;
    void fromJsonObject(QJsonObject json) override;
    void fromJson(QString jsonString) override;

    QString getId() const;
    void setId(const QString &id);
    bool is_id_Set() const;
    bool is_id_Valid() const;

    QString getPassword() const;
    void setPassword(const QString &password);
    bool is_password_Set() const;
    bool is_password_Valid() const;

    QString getName() const;
    void setName(const QString &name);
    bool is_name_Set() const;
    bool is_name_Valid() const;

    QString getAge() const;
    void setAge(const QString &age);
    bool is_age_Set() const;
    bool is_age_Valid() const;

    QString getGender() const;
    void setGender(const QString &gender);
    bool is_gender_Set() const;
    bool is_gender_Valid() const;

    QString getPhone() const;
    void setPhone(const QString &phone);
    bool is_phone_Set() const;
    bool is_phone_Valid() const;

    QString getAddress() const;
    void setAddress(const QString &address);
    bool is_address_Set() const;
    bool is_address_Valid() const;

    virtual bool isSet() const override;
    virtual bool isValid() const override;

private:
    void initializeModel();

    QString id;
    bool m_id_isSet;
    bool m_id_isValid;

    QString password;
    bool m_password_isSet;
    bool m_password_isValid;

    QString name;
    bool m_name_isSet;
    bool m_name_isValid;

    QString age;
    bool m_age_isSet;
    bool m_age_isValid;

    QString gender;
    bool m_gender_isSet;
    bool m_gender_isValid;

    QString phone;
    bool m_phone_isSet;
    bool m_phone_isValid;

    QString address;
    bool m_address_isSet;
    bool m_address_isValid;
};

} // namespace HttpServer

Q_DECLARE_METATYPE(HttpServer::User)

#endif // User_H
