/**
 * SmMed
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

#include <QJsonArray>
#include <QJsonDocument>
#include <QJsonObject>
#include <QVariantMap>
#include <QDebug>

#include "AppointmentApiHandler.h"
#include "AppointmentApiRequest.h"

namespace HttpServer {

AppointmentApiHandler::AppointmentApiHandler(){

}

AppointmentApiHandler::~AppointmentApiHandler(){

}

void AppointmentApiHandler::appointmentDoctorGet(QString doctor_id, qint32 office) {
    Q_UNUSED(doctor_id);
    Q_UNUSED(office);
    auto reqObj = qobject_cast<AppointmentApiRequest*>(sender());
    if( reqObj != nullptr ) 
    { 
        Inline_response_200_11 res;
        reqObj->appointmentDoctorGetResponse(res);
    }    
}
void AppointmentApiHandler::appointmentIdDelete(QString id) {
    Q_UNUSED(id);
    auto reqObj = qobject_cast<AppointmentApiRequest*>(sender());
    if( reqObj != nullptr ) 
    { 
        Object res;
        reqObj->appointmentIdDeleteResponse(res);
    }    
}
void AppointmentApiHandler::appointmentPatientGet(qint32 patient_id, qint32 office) {
    Q_UNUSED(patient_id);
    Q_UNUSED(office);
    auto reqObj = qobject_cast<AppointmentApiRequest*>(sender());
    if( reqObj != nullptr ) 
    { 
        Inline_response_200_11 res;
        reqObj->appointmentPatientGetResponse(res);
    }    
}
void AppointmentApiHandler::appointmentPost(Inline_object_4 inline_object_4) {
    Q_UNUSED(inline_object_4);
    auto reqObj = qobject_cast<AppointmentApiRequest*>(sender());
    if( reqObj != nullptr ) 
    { 
        Inline_response_200_12 res;
        reqObj->appointmentPostResponse(res);
    }    
}


}
