/**
 * SmMed
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

#ifndef _DefaultApiHandler_H
#define _DefaultApiHandler_H

#include <QObject>

#include "Inline_response_200.h"
#include "Inline_response_200_2.h"
#include "Inline_response_200_4.h"
#include "Inline_response_404.h"
#include "Inline_response_404_1.h"
#include "Object.h"
#include <QString>

namespace HttpServer {

class DefaultApiHandler : public QObject
{
    Q_OBJECT
    
public:
    DefaultApiHandler();
    virtual ~DefaultApiHandler();


public slots:
    virtual void loginPost(QString id, QString password, Object body);
    virtual void notificationsGet(QString date);
    virtual void officeIdGet(qint32 id);
    

};

}

#endif // _DefaultApiHandler_H
