/**
 * SmMed
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

#include <QJsonArray>
#include <QJsonDocument>
#include <QJsonObject>
#include <QVariantMap>
#include <QDebug>

#include "DefaultApiHandler.h"
#include "DefaultApiRequest.h"

namespace HttpServer {

DefaultApiHandler::DefaultApiHandler(){

}

DefaultApiHandler::~DefaultApiHandler(){

}

void DefaultApiHandler::loginPost(QString id, QString password, Object body) {
    Q_UNUSED(id);
    Q_UNUSED(password);
    Q_UNUSED(body);
    auto reqObj = qobject_cast<DefaultApiRequest*>(sender());
    if( reqObj != nullptr ) 
    { 
        Inline_response_200_2 res;
        reqObj->loginPostResponse(res);
    }    
}
void DefaultApiHandler::notificationsGet(QString date) {
    Q_UNUSED(date);
    auto reqObj = qobject_cast<DefaultApiRequest*>(sender());
    if( reqObj != nullptr ) 
    { 
        Inline_response_200 res;
        reqObj->notificationsGetResponse(res);
    }    
}
void DefaultApiHandler::officeIdGet(qint32 id) {
    Q_UNUSED(id);
    auto reqObj = qobject_cast<DefaultApiRequest*>(sender());
    if( reqObj != nullptr ) 
    { 
        Inline_response_200_4 res;
        reqObj->officeIdGetResponse(res);
    }    
}


}
