/**
 * SmMed
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

#include <QJsonArray>
#include <QJsonDocument>
#include <QJsonObject>
#include <QVariantMap>
#include <QDebug>

#include "DocterApiHandler.h"
#include "DocterApiRequest.h"

namespace HttpServer {

DocterApiHandler::DocterApiHandler(){

}

DocterApiHandler::~DocterApiHandler(){

}

void DocterApiHandler::doctorGet(qint32 office) {
    Q_UNUSED(office);
    auto reqObj = qobject_cast<DocterApiRequest*>(sender());
    if( reqObj != nullptr ) 
    { 
        Inline_response_200_7 res;
        reqObj->doctorGetResponse(res);
    }    
}
void DocterApiHandler::doctorIdGet(QString id) {
    Q_UNUSED(id);
    auto reqObj = qobject_cast<DocterApiRequest*>(sender());
    if( reqObj != nullptr ) 
    { 
        Inline_response_200_1 res;
        reqObj->doctorIdGetResponse(res);
    }    
}
void DocterApiHandler::doctorPost(Inline_object_3 inline_object_3) {
    Q_UNUSED(inline_object_3);
    auto reqObj = qobject_cast<DocterApiRequest*>(sender());
    if( reqObj != nullptr ) 
    { 
        Inline_response_200_8 res;
        reqObj->doctorPostResponse(res);
    }    
}
void DocterApiHandler::doctorPut(Inline_object_2 inline_object_2) {
    Q_UNUSED(inline_object_2);
    auto reqObj = qobject_cast<DocterApiRequest*>(sender());
    if( reqObj != nullptr ) 
    { 
        Inline_response_200_5 res;
        reqObj->doctorPutResponse(res);
    }    
}


}
