/**
 * SmMed
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

#ifndef _DocterApiHandler_H
#define _DocterApiHandler_H

#include <QObject>

#include "Inline_object_2.h"
#include "Inline_object_3.h"
#include "Inline_response_200_1.h"
#include "Inline_response_200_5.h"
#include "Inline_response_200_7.h"
#include "Inline_response_200_8.h"
#include "Object.h"
#include <QString>

namespace HttpServer {

class DocterApiHandler : public QObject
{
    Q_OBJECT
    
public:
    DocterApiHandler();
    virtual ~DocterApiHandler();


public slots:
    virtual void doctorGet(qint32 office);
    virtual void doctorIdGet(QString id);
    virtual void doctorPost(Inline_object_3 inline_object_3);
    virtual void doctorPut(Inline_object_2 inline_object_2);
    

};

}

#endif // _DocterApiHandler_H
