/**
 * SmMed
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

#ifndef _FileApiHandler_H
#define _FileApiHandler_H

#include <QObject>

#include "HttpFileElement.h"
#include "Inline_response_200_3.h"
#include "Object.h"
#include <QString>

namespace HttpServer {

class FileApiHandler : public QObject
{
    Q_OBJECT
    
public:
    FileApiHandler();
    virtual ~FileApiHandler();


public slots:
    virtual void fileGet(QString uuid, QString apikey);
    virtual void filePost(QString name, QString doctor_id, QString patient_id, QString type, QString apikey, QString appointment_id, HttpFileElement body);
    

};

}

#endif // _FileApiHandler_H
