/**
 * SmMed
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

#ifndef _PatientApiHandler_H
#define _PatientApiHandler_H

#include <QObject>

#include "Inline_object_5.h"
#include "Object.h"
#include <QString>

namespace HttpServer {

class PatientApiHandler : public QObject
{
    Q_OBJECT
    
public:
    PatientApiHandler();
    virtual ~PatientApiHandler();


public slots:
    virtual void patientPost(Inline_object_5 inline_object_5);
    

};

}

#endif // _PatientApiHandler_H
