/**
 * SmMed
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

#include <QJsonArray>
#include <QJsonDocument>
#include <QJsonObject>
#include <QVariantMap>
#include <QDebug>

#include "PatientApiHandler.h"
#include "PatientApiRequest.h"

namespace HttpServer {

PatientApiHandler::PatientApiHandler(){

}

PatientApiHandler::~PatientApiHandler(){

}

void PatientApiHandler::patientPost(Inline_object_5 inline_object_5) {
    Q_UNUSED(inline_object_5);
    auto reqObj = qobject_cast<PatientApiRequest*>(sender());
    if( reqObj != nullptr ) 
    { 
        Object res;
        reqObj->patientPostResponse(res);
    }    
}


}
