/**
 * SmMed
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

#include <QJsonArray>
#include <QJsonDocument>
#include <QJsonObject>
#include <QVariantMap>
#include <QDebug>

#include "UserApiHandler.h"
#include "UserApiRequest.h"

namespace HttpServer {

UserApiHandler::UserApiHandler(){

}

UserApiHandler::~UserApiHandler(){

}

void UserApiHandler::userIdGet(QString id) {
    Q_UNUSED(id);
    auto reqObj = qobject_cast<UserApiRequest*>(sender());
    if( reqObj != nullptr ) 
    { 
        Inline_response_200_3 res;
        reqObj->userIdGetResponse(res);
    }    
}
void UserApiHandler::userPost(Inline_object_1 inline_object_1) {
    Q_UNUSED(inline_object_1);
    auto reqObj = qobject_cast<UserApiRequest*>(sender());
    if( reqObj != nullptr ) 
    { 
        Inline_response_200_6 res;
        reqObj->userPostResponse(res);
    }    
}
void UserApiHandler::userPut(Inline_object inline_object) {
    Q_UNUSED(inline_object);
    auto reqObj = qobject_cast<UserApiRequest*>(sender());
    if( reqObj != nullptr ) 
    { 
        Inline_response_200_5 res;
        reqObj->userPutResponse(res);
    }    
}


}
