/**
 * SmMed
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

#include <QJsonArray>
#include <QJsonDocument>
#include <QJsonObject>
#include <QVariantMap>
#include <QDebug>

#include "UserApiHandler.h"
#include "UserApiRequest.h"
#include"global.h"
namespace HttpServer {

UserApiHandler::UserApiHandler(){

}

UserApiHandler::~UserApiHandler(){

}

void UserApiHandler::userPost(Inline_object inline_object) {
    QString id = inline_object.getId();
    QString password = inline_object.getPassword();
    Q_UNUSED(inline_object);
    auto reqObj = qobject_cast<UserApiRequest*>(sender());
    if( reqObj != nullptr )
    {
        QSharedPointer<QJsonDocument> jsondoc;
        try {
            jsondoc = dbserver->set_userpassword(id,password);
        } catch (std::exception e) {
            QString errortext = "register failed!";
            Inline_response_200_1 res;
            qDebug() << errortext;
            QByteArray bytearray;
            reqObj->userPostError(res,QNetworkReply::NetworkError::RecodeNotFound,errortext);
            qDebug() << errortext;
            return;
        }
        QString resstr = QString(jsondoc->toJson());
        qDebug() << resstr;
        Inline_response_200_1 res(resstr);
        reqObj->userPostResponse(res);
    }
}


}
