/**
 * SmMed
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

#ifndef _UserApiHandler_H
#define _UserApiHandler_H

#include <QObject>

#include "Inline_object.h"
#include "Inline_response_200_1.h"
#include "Object.h"
#include <QString>

namespace HttpServer {

class UserApiHandler : public QObject
{
    Q_OBJECT
    
public:
    UserApiHandler();
    virtual ~UserApiHandler();


public slots:
    virtual void userPost(Inline_object inline_object);
    

};

}

#endif // _UserApiHandler_H
