/**
 * SmMed
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

#include "Appointment.h"

#include <QDebug>
#include <QJsonArray>
#include <QJsonDocument>
#include <QObject>

#include "Helpers.h"

namespace HttpServer {

Appointment::Appointment(QString json) {
    this->initializeModel();
    this->fromJson(json);
}

Appointment::Appointment() {
    this->initializeModel();
}

Appointment::~Appointment() {}

void Appointment::initializeModel() {

    m_id_isSet = false;
    m_id_isValid = false;

    m_date_isSet = false;
    m_date_isValid = false;

    m_patient_id_isSet = false;
    m_patient_id_isValid = false;

    m_doctor_id_isSet = false;
    m_doctor_id_isValid = false;

    m_number_isSet = false;
    m_number_isValid = false;

    m_office_isSet = false;
    m_office_isValid = false;
}

void Appointment::fromJson(QString jsonString) {
    QByteArray array(jsonString.toStdString().c_str());
    QJsonDocument doc = QJsonDocument::fromJson(array);
    QJsonObject jsonObject = doc.object();
    this->fromJsonObject(jsonObject);
}

void Appointment::fromJsonObject(QJsonObject json) {

    m_id_isValid = ::HttpServer::fromJsonValue(id, json[QString("id")]);
    m_id_isSet = !json[QString("id")].isNull() && m_id_isValid;

    m_date_isValid = ::HttpServer::fromJsonValue(date, json[QString("date")]);
    m_date_isSet = !json[QString("date")].isNull() && m_date_isValid;

    m_patient_id_isValid = ::HttpServer::fromJsonValue(patient_id, json[QString("patient_id")]);
    m_patient_id_isSet = !json[QString("patient_id")].isNull() && m_patient_id_isValid;

    m_doctor_id_isValid = ::HttpServer::fromJsonValue(doctor_id, json[QString("doctor_id")]);
    m_doctor_id_isSet = !json[QString("doctor_id")].isNull() && m_doctor_id_isValid;

    m_number_isValid = ::HttpServer::fromJsonValue(number, json[QString("number")]);
    m_number_isSet = !json[QString("number")].isNull() && m_number_isValid;

    m_office_isValid = ::HttpServer::fromJsonValue(office, json[QString("office")]);
    m_office_isSet = !json[QString("office")].isNull() && m_office_isValid;
}

QString Appointment::asJson() const {
    QJsonObject obj = this->asJsonObject();
    QJsonDocument doc(obj);
    QByteArray bytes = doc.toJson();
    return QString(bytes);
}

QJsonObject Appointment::asJsonObject() const {
    QJsonObject obj;
    if (m_id_isSet) {
        obj.insert(QString("id"), ::HttpServer::toJsonValue(id));
    }
    if (m_date_isSet) {
        obj.insert(QString("date"), ::HttpServer::toJsonValue(date));
    }
    if (m_patient_id_isSet) {
        obj.insert(QString("patient_id"), ::HttpServer::toJsonValue(patient_id));
    }
    if (m_doctor_id_isSet) {
        obj.insert(QString("doctor_id"), ::HttpServer::toJsonValue(doctor_id));
    }
    if (m_number_isSet) {
        obj.insert(QString("number"), ::HttpServer::toJsonValue(number));
    }
    if (m_office_isSet) {
        obj.insert(QString("office"), ::HttpServer::toJsonValue(office));
    }
    return obj;
}

qint32 Appointment::getId() const {
    return id;
}
void Appointment::setId(const qint32 &id) {
    this->id = id;
    this->m_id_isSet = true;
}

bool Appointment::is_id_Set() const{
    return m_id_isSet;
}

bool Appointment::is_id_Valid() const{
    return m_id_isValid;
}

QString Appointment::getDate() const {
    return date;
}
void Appointment::setDate(const QString &date) {
    this->date = date;
    this->m_date_isSet = true;
}

bool Appointment::is_date_Set() const{
    return m_date_isSet;
}

bool Appointment::is_date_Valid() const{
    return m_date_isValid;
}

qint32 Appointment::getPatientId() const {
    return patient_id;
}
void Appointment::setPatientId(const qint32 &patient_id) {
    this->patient_id = patient_id;
    this->m_patient_id_isSet = true;
}

bool Appointment::is_patient_id_Set() const{
    return m_patient_id_isSet;
}

bool Appointment::is_patient_id_Valid() const{
    return m_patient_id_isValid;
}

QString Appointment::getDoctorId() const {
    return doctor_id;
}
void Appointment::setDoctorId(const QString &doctor_id) {
    this->doctor_id = doctor_id;
    this->m_doctor_id_isSet = true;
}

bool Appointment::is_doctor_id_Set() const{
    return m_doctor_id_isSet;
}

bool Appointment::is_doctor_id_Valid() const{
    return m_doctor_id_isValid;
}

qint32 Appointment::getNumber() const {
    return number;
}
void Appointment::setNumber(const qint32 &number) {
    this->number = number;
    this->m_number_isSet = true;
}

bool Appointment::is_number_Set() const{
    return m_number_isSet;
}

bool Appointment::is_number_Valid() const{
    return m_number_isValid;
}

QString Appointment::getOffice() const {
    return office;
}
void Appointment::setOffice(const QString &office) {
    this->office = office;
    this->m_office_isSet = true;
}

bool Appointment::is_office_Set() const{
    return m_office_isSet;
}

bool Appointment::is_office_Valid() const{
    return m_office_isValid;
}

bool Appointment::isSet() const {
    bool isObjectUpdated = false;
    do {
        if (m_id_isSet) {
            isObjectUpdated = true;
            break;
        }

        if (m_date_isSet) {
            isObjectUpdated = true;
            break;
        }

        if (m_patient_id_isSet) {
            isObjectUpdated = true;
            break;
        }

        if (m_doctor_id_isSet) {
            isObjectUpdated = true;
            break;
        }

        if (m_number_isSet) {
            isObjectUpdated = true;
            break;
        }

        if (m_office_isSet) {
            isObjectUpdated = true;
            break;
        }
    } while (false);
    return isObjectUpdated;
}

bool Appointment::isValid() const {
    // only required properties are required for the object to be considered valid
    return m_id_isValid && m_date_isValid && m_patient_id_isValid && m_doctor_id_isValid && m_number_isValid && m_office_isValid && true;
}

} // namespace HttpServer
