/**
 * SmMed
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

#include "Inline_object_2.h"

#include <QDebug>
#include <QJsonArray>
#include <QJsonDocument>
#include <QObject>

#include "Helpers.h"

namespace HttpServer {

Inline_object_2::Inline_object_2(QString json) {
    this->initializeModel();
    this->fromJson(json);
}

Inline_object_2::Inline_object_2() {
    this->initializeModel();
}

Inline_object_2::~Inline_object_2() {}

void Inline_object_2::initializeModel() {

    m_id_isSet = false;
    m_id_isValid = false;

    m_password_isSet = false;
    m_password_isValid = false;

    m_name_isSet = false;
    m_name_isValid = false;

    m_gender_isSet = false;
    m_gender_isValid = false;

    m_office_isSet = false;
    m_office_isValid = false;

    m_zc_isSet = false;
    m_zc_isValid = false;

    m_describe_isSet = false;
    m_describe_isValid = false;
}

void Inline_object_2::fromJson(QString jsonString) {
    QByteArray array(jsonString.toStdString().c_str());
    QJsonDocument doc = QJsonDocument::fromJson(array);
    QJsonObject jsonObject = doc.object();
    this->fromJsonObject(jsonObject);
}

void Inline_object_2::fromJsonObject(QJsonObject json) {

    m_id_isValid = ::HttpServer::fromJsonValue(id, json[QString("id")]);
    m_id_isSet = !json[QString("id")].isNull() && m_id_isValid;

    m_password_isValid = ::HttpServer::fromJsonValue(password, json[QString("password")]);
    m_password_isSet = !json[QString("password")].isNull() && m_password_isValid;

    m_name_isValid = ::HttpServer::fromJsonValue(name, json[QString("name")]);
    m_name_isSet = !json[QString("name")].isNull() && m_name_isValid;

    m_gender_isValid = ::HttpServer::fromJsonValue(gender, json[QString("gender")]);
    m_gender_isSet = !json[QString("gender")].isNull() && m_gender_isValid;

    m_office_isValid = ::HttpServer::fromJsonValue(office, json[QString("office")]);
    m_office_isSet = !json[QString("office")].isNull() && m_office_isValid;

    m_zc_isValid = ::HttpServer::fromJsonValue(zc, json[QString("zc")]);
    m_zc_isSet = !json[QString("zc")].isNull() && m_zc_isValid;

    m_describe_isValid = ::HttpServer::fromJsonValue(describe, json[QString("describe")]);
    m_describe_isSet = !json[QString("describe")].isNull() && m_describe_isValid;
}

QString Inline_object_2::asJson() const {
    QJsonObject obj = this->asJsonObject();
    QJsonDocument doc(obj);
    QByteArray bytes = doc.toJson();
    return QString(bytes);
}

QJsonObject Inline_object_2::asJsonObject() const {
    QJsonObject obj;
    if (m_id_isSet) {
        obj.insert(QString("id"), ::HttpServer::toJsonValue(id));
    }
    if (m_password_isSet) {
        obj.insert(QString("password"), ::HttpServer::toJsonValue(password));
    }
    if (m_name_isSet) {
        obj.insert(QString("name"), ::HttpServer::toJsonValue(name));
    }
    if (m_gender_isSet) {
        obj.insert(QString("gender"), ::HttpServer::toJsonValue(gender));
    }
    if (m_office_isSet) {
        obj.insert(QString("office"), ::HttpServer::toJsonValue(office));
    }
    if (m_zc_isSet) {
        obj.insert(QString("zc"), ::HttpServer::toJsonValue(zc));
    }
    if (m_describe_isSet) {
        obj.insert(QString("describe"), ::HttpServer::toJsonValue(describe));
    }
    return obj;
}

QString Inline_object_2::getId() const {
    return id;
}
void Inline_object_2::setId(const QString &id) {
    this->id = id;
    this->m_id_isSet = true;
}

bool Inline_object_2::is_id_Set() const{
    return m_id_isSet;
}

bool Inline_object_2::is_id_Valid() const{
    return m_id_isValid;
}

QString Inline_object_2::getPassword() const {
    return password;
}
void Inline_object_2::setPassword(const QString &password) {
    this->password = password;
    this->m_password_isSet = true;
}

bool Inline_object_2::is_password_Set() const{
    return m_password_isSet;
}

bool Inline_object_2::is_password_Valid() const{
    return m_password_isValid;
}

QString Inline_object_2::getName() const {
    return name;
}
void Inline_object_2::setName(const QString &name) {
    this->name = name;
    this->m_name_isSet = true;
}

bool Inline_object_2::is_name_Set() const{
    return m_name_isSet;
}

bool Inline_object_2::is_name_Valid() const{
    return m_name_isValid;
}

QString Inline_object_2::getGender() const {
    return gender;
}
void Inline_object_2::setGender(const QString &gender) {
    this->gender = gender;
    this->m_gender_isSet = true;
}

bool Inline_object_2::is_gender_Set() const{
    return m_gender_isSet;
}

bool Inline_object_2::is_gender_Valid() const{
    return m_gender_isValid;
}

QString Inline_object_2::getOffice() const {
    return office;
}
void Inline_object_2::setOffice(const QString &office) {
    this->office = office;
    this->m_office_isSet = true;
}

bool Inline_object_2::is_office_Set() const{
    return m_office_isSet;
}

bool Inline_object_2::is_office_Valid() const{
    return m_office_isValid;
}

QString Inline_object_2::getZc() const {
    return zc;
}
void Inline_object_2::setZc(const QString &zc) {
    this->zc = zc;
    this->m_zc_isSet = true;
}

bool Inline_object_2::is_zc_Set() const{
    return m_zc_isSet;
}

bool Inline_object_2::is_zc_Valid() const{
    return m_zc_isValid;
}

QString Inline_object_2::getDescribe() const {
    return describe;
}
void Inline_object_2::setDescribe(const QString &describe) {
    this->describe = describe;
    this->m_describe_isSet = true;
}

bool Inline_object_2::is_describe_Set() const{
    return m_describe_isSet;
}

bool Inline_object_2::is_describe_Valid() const{
    return m_describe_isValid;
}

bool Inline_object_2::isSet() const {
    bool isObjectUpdated = false;
    do {
        if (m_id_isSet) {
            isObjectUpdated = true;
            break;
        }

        if (m_password_isSet) {
            isObjectUpdated = true;
            break;
        }

        if (m_name_isSet) {
            isObjectUpdated = true;
            break;
        }

        if (m_gender_isSet) {
            isObjectUpdated = true;
            break;
        }

        if (m_office_isSet) {
            isObjectUpdated = true;
            break;
        }

        if (m_zc_isSet) {
            isObjectUpdated = true;
            break;
        }

        if (m_describe_isSet) {
            isObjectUpdated = true;
            break;
        }
    } while (false);
    return isObjectUpdated;
}

bool Inline_object_2::isValid() const {
    // only required properties are required for the object to be considered valid
    return m_id_isValid && m_password_isValid && m_name_isValid && m_gender_isValid && m_office_isValid && m_zc_isValid && m_describe_isValid && true;
}

} // namespace HttpServer
