/**
 * SmMed
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * Inline_response_200_1.h
 *
 * 
 */

#ifndef Inline_response_200_1_H
#define Inline_response_200_1_H

#include <QJsonObject>

#include <QString>

#include "Enum.h"
#include "Object.h"

namespace HttpServer {

class Inline_response_200_1 : public Object {
public:
    Inline_response_200_1();
    Inline_response_200_1(QString json);
    ~Inline_response_200_1() override;

    QString asJson() const override;
    QJsonObject asJsonObject() const override;
    void fromJsonObject(QJsonObject json) override;
    void fromJson(QString jsonString) override;

    QString getApikey() const;
    void setApikey(const QString &apikey);
    bool is_apikey_Set() const;
    bool is_apikey_Valid() const;

    QString getId() const;
    void setId(const QString &id);
    bool is_id_Set() const;
    bool is_id_Valid() const;

    QString getDate() const;
    void setDate(const QString &date);
    bool is_date_Set() const;
    bool is_date_Valid() const;

    virtual bool isSet() const override;
    virtual bool isValid() const override;

private:
    void initializeModel();

    QString apikey;
    bool m_apikey_isSet;
    bool m_apikey_isValid;

    QString id;
    bool m_id_isSet;
    bool m_id_isValid;

    QString date;
    bool m_date_isSet;
    bool m_date_isValid;
};

} // namespace HttpServer

Q_DECLARE_METATYPE(HttpServer::Inline_response_200_1)

#endif // Inline_response_200_1_H
