/**
 * SmMed
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * Inline_object_4.h
 *
 * 
 */

#ifndef Inline_object_4_H
#define Inline_object_4_H

#include <QJsonObject>

#include <QString>

#include "Enum.h"
#include "Object.h"

namespace HttpServer {

class Inline_object_4 : public Object {
public:
    Inline_object_4();
    Inline_object_4(QString json);
    ~Inline_object_4() override;

    QString asJson() const override;
    QJsonObject asJsonObject() const override;
    void fromJsonObject(QJsonObject json) override;
    void fromJson(QString jsonString) override;

    qint32 getId() const;
    void setId(const qint32 &id);
    bool is_id_Set() const;
    bool is_id_Valid() const;

    QString getDate() const;
    void setDate(const QString &date);
    bool is_date_Set() const;
    bool is_date_Valid() const;

    qint32 getPatientId() const;
    void setPatientId(const qint32 &patient_id);
    bool is_patient_id_Set() const;
    bool is_patient_id_Valid() const;

    QString getDoctorId() const;
    void setDoctorId(const QString &doctor_id);
    bool is_doctor_id_Set() const;
    bool is_doctor_id_Valid() const;

    qint32 getNumber() const;
    void setNumber(const qint32 &number);
    bool is_number_Set() const;
    bool is_number_Valid() const;

    QString getOffice() const;
    void setOffice(const QString &office);
    bool is_office_Set() const;
    bool is_office_Valid() const;

    virtual bool isSet() const override;
    virtual bool isValid() const override;

private:
    void initializeModel();

    qint32 id;
    bool m_id_isSet;
    bool m_id_isValid;

    QString date;
    bool m_date_isSet;
    bool m_date_isValid;

    qint32 patient_id;
    bool m_patient_id_isSet;
    bool m_patient_id_isValid;

    QString doctor_id;
    bool m_doctor_id_isSet;
    bool m_doctor_id_isValid;

    qint32 number;
    bool m_number_isSet;
    bool m_number_isValid;

    QString office;
    bool m_office_isSet;
    bool m_office_isValid;
};

} // namespace HttpServer

Q_DECLARE_METATYPE(HttpServer::Inline_object_4)

#endif // Inline_object_4_H
