/**
 * SmMed
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

#include "Inline_response_200_9.h"

#include <QDebug>
#include <QJsonArray>
#include <QJsonDocument>
#include <QObject>

#include "Helpers.h"

namespace HttpServer {

Inline_response_200_9::Inline_response_200_9(QString json) {
    this->initializeModel();
    this->fromJson(json);
}

Inline_response_200_9::Inline_response_200_9() {
    this->initializeModel();
}

Inline_response_200_9::~Inline_response_200_9() {}

void Inline_response_200_9::initializeModel() {

    m_id_isSet = false;
    m_id_isValid = false;
}

void Inline_response_200_9::fromJson(QString jsonString) {
    QByteArray array(jsonString.toStdString().c_str());
    QJsonDocument doc = QJsonDocument::fromJson(array);
    QJsonObject jsonObject = doc.object();
    this->fromJsonObject(jsonObject);
}

void Inline_response_200_9::fromJsonObject(QJsonObject json) {

    m_id_isValid = ::HttpServer::fromJsonValue(id, json[QString("id")]);
    m_id_isSet = !json[QString("id")].isNull() && m_id_isValid;
}

QString Inline_response_200_9::asJson() const {
    QJsonObject obj = this->asJsonObject();
    QJsonDocument doc(obj);
    QByteArray bytes = doc.toJson();
    return QString(bytes);
}

QJsonObject Inline_response_200_9::asJsonObject() const {
    QJsonObject obj;
    if (m_id_isSet) {
        obj.insert(QString("id"), ::HttpServer::toJsonValue(id));
    }
    return obj;
}

qint32 Inline_response_200_9::getId() const {
    return id;
}
void Inline_response_200_9::setId(const qint32 &id) {
    this->id = id;
    this->m_id_isSet = true;
}

bool Inline_response_200_9::is_id_Set() const{
    return m_id_isSet;
}

bool Inline_response_200_9::is_id_Valid() const{
    return m_id_isValid;
}

bool Inline_response_200_9::isSet() const {
    bool isObjectUpdated = false;
    do {
        if (m_id_isSet) {
            isObjectUpdated = true;
            break;
        }
    } while (false);
    return isObjectUpdated;
}

bool Inline_response_200_9::isValid() const {
    // only required properties are required for the object to be considered valid
    return m_id_isValid && true;
}

} // namespace HttpServer
