/**
 * SmMed
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * Inline_response_200_9.h
 *
 * 
 */

#ifndef Inline_response_200_9_H
#define Inline_response_200_9_H

#include <QJsonObject>


#include "Enum.h"
#include "Object.h"

namespace HttpServer {

class Inline_response_200_9 : public Object {
public:
    Inline_response_200_9();
    Inline_response_200_9(QString json);
    ~Inline_response_200_9() override;

    QString asJson() const override;
    QJsonObject asJsonObject() const override;
    void fromJsonObject(QJsonObject json) override;
    void fromJson(QString jsonString) override;

    qint32 getId() const;
    void setId(const qint32 &id);
    bool is_id_Set() const;
    bool is_id_Valid() const;

    virtual bool isSet() const override;
    virtual bool isValid() const override;

private:
    void initializeModel();

    qint32 id;
    bool m_id_isSet;
    bool m_id_isValid;
};

} // namespace HttpServer

Q_DECLARE_METATYPE(HttpServer::Inline_response_200_9)

#endif // Inline_response_200_9_H
