/**
 * SmMed
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

#include "Inline_response_200_4.h"

#include <QDebug>
#include <QJsonArray>
#include <QJsonDocument>
#include <QObject>

#include "Helpers.h"

namespace HttpServer {

Inline_response_200_4::Inline_response_200_4(QString json) {
    this->initializeModel();
    this->fromJson(json);
}

Inline_response_200_4::Inline_response_200_4() {
    this->initializeModel();
}

Inline_response_200_4::~Inline_response_200_4() {}

void Inline_response_200_4::initializeModel() {

    m_name_isSet = false;
    m_name_isValid = false;
}

void Inline_response_200_4::fromJson(QString jsonString) {
    QByteArray array(jsonString.toStdString().c_str());
    QJsonDocument doc = QJsonDocument::fromJson(array);
    QJsonObject jsonObject = doc.object();
    this->fromJsonObject(jsonObject);
}

void Inline_response_200_4::fromJsonObject(QJsonObject json) {

    m_name_isValid = ::HttpServer::fromJsonValue(name, json[QString("name")]);
    m_name_isSet = !json[QString("name")].isNull() && m_name_isValid;
}

QString Inline_response_200_4::asJson() const {
    QJsonObject obj = this->asJsonObject();
    QJsonDocument doc(obj);
    QByteArray bytes = doc.toJson();
    return QString(bytes);
}

QJsonObject Inline_response_200_4::asJsonObject() const {
    QJsonObject obj;
    if (m_name_isSet) {
        obj.insert(QString("name"), ::HttpServer::toJsonValue(name));
    }
    return obj;
}

QString Inline_response_200_4::getName() const {
    return name;
}
void Inline_response_200_4::setName(const QString &name) {
    this->name = name;
    this->m_name_isSet = true;
}

bool Inline_response_200_4::is_name_Set() const{
    return m_name_isSet;
}

bool Inline_response_200_4::is_name_Valid() const{
    return m_name_isValid;
}

bool Inline_response_200_4::isSet() const {
    bool isObjectUpdated = false;
    do {
        if (m_name_isSet) {
            isObjectUpdated = true;
            break;
        }
    } while (false);
    return isObjectUpdated;
}

bool Inline_response_200_4::isValid() const {
    // only required properties are required for the object to be considered valid
    return m_name_isValid && true;
}

} // namespace HttpServer
