/**
 * SmMed
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * Inline_response_200_10_data.h
 *
 * 
 */

#ifndef Inline_response_200_10_data_H
#define Inline_response_200_10_data_H

#include <QJsonObject>

#include <QString>

#include "Enum.h"
#include "Object.h"

namespace HttpServer {

class Inline_response_200_10_data : public Object {
public:
    Inline_response_200_10_data();
    Inline_response_200_10_data(QString json);
    ~Inline_response_200_10_data() override;

    QString asJson() const override;
    QJsonObject asJsonObject() const override;
    void fromJsonObject(QJsonObject json) override;
    void fromJson(QString jsonString) override;

    qint32 getId() const;
    void setId(const qint32 &id);
    bool is_id_Set() const;
    bool is_id_Valid() const;

    QString getName() const;
    void setName(const QString &name);
    bool is_name_Set() const;
    bool is_name_Valid() const;

    QString getDoctorId() const;
    void setDoctorId(const QString &doctor_id);
    bool is_doctor_id_Set() const;
    bool is_doctor_id_Valid() const;

    qint32 getPatientId() const;
    void setPatientId(const qint32 &patient_id);
    bool is_patient_id_Set() const;
    bool is_patient_id_Valid() const;

    qint32 getType() const;
    void setType(const qint32 &type);
    bool is_type_Set() const;
    bool is_type_Valid() const;

    virtual bool isSet() const override;
    virtual bool isValid() const override;

private:
    void initializeModel();

    qint32 id;
    bool m_id_isSet;
    bool m_id_isValid;

    QString name;
    bool m_name_isSet;
    bool m_name_isValid;

    QString doctor_id;
    bool m_doctor_id_isSet;
    bool m_doctor_id_isValid;

    qint32 patient_id;
    bool m_patient_id_isSet;
    bool m_patient_id_isValid;

    qint32 type;
    bool m_type_isSet;
    bool m_type_isValid;
};

} // namespace HttpServer

Q_DECLARE_METATYPE(HttpServer::Inline_response_200_10_data)

#endif // Inline_response_200_10_data_H
