/**
 * SmMed
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

#include "Inline_response_200.h"

#include <QDebug>
#include <QJsonArray>
#include <QJsonDocument>
#include <QObject>

#include "Helpers.h"

namespace HttpServer {

Inline_response_200::Inline_response_200(QString json) {
    this->initializeModel();
    this->fromJson(json);
}

Inline_response_200::Inline_response_200() {
    this->initializeModel();
}

Inline_response_200::~Inline_response_200() {}

void Inline_response_200::initializeModel() {

    m_apikey_isSet = false;
    m_apikey_isValid = false;
}

void Inline_response_200::fromJson(QString jsonString) {
    QByteArray array(jsonString.toStdString().c_str());
    QJsonDocument doc = QJsonDocument::fromJson(array);
    QJsonObject jsonObject = doc.object();
    this->fromJsonObject(jsonObject);
}

void Inline_response_200::fromJsonObject(QJsonObject json) {

    m_apikey_isValid = ::HttpServer::fromJsonValue(apikey, json[QString("apikey")]);
    m_apikey_isSet = !json[QString("apikey")].isNull() && m_apikey_isValid;
}

QString Inline_response_200::asJson() const {
    QJsonObject obj = this->asJsonObject();
    QJsonDocument doc(obj);
    QByteArray bytes = doc.toJson();
    return QString(bytes);
}

QJsonObject Inline_response_200::asJsonObject() const {
    QJsonObject obj;
    if (m_apikey_isSet) {
        obj.insert(QString("apikey"), ::HttpServer::toJsonValue(apikey));
    }
    return obj;
}

QString Inline_response_200::getApikey() const {
    return apikey;
}
void Inline_response_200::setApikey(const QString &apikey) {
    this->apikey = apikey;
    this->m_apikey_isSet = true;
}

bool Inline_response_200::is_apikey_Set() const{
    return m_apikey_isSet;
}

bool Inline_response_200::is_apikey_Valid() const{
    return m_apikey_isValid;
}

bool Inline_response_200::isSet() const {
    bool isObjectUpdated = false;
    do {
        if (m_apikey_isSet) {
            isObjectUpdated = true;
            break;
        }
    } while (false);
    return isObjectUpdated;
}

bool Inline_response_200::isValid() const {
    // only required properties are required for the object to be considered valid
    return m_apikey_isValid && true;
}

} // namespace HttpServer
