/**
 * SmMed
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

#ifndef OAI_OAIDefaultApiHandler_H
#define OAI_OAIDefaultApiHandler_H

#include <QObject>

#include "OAIInline_response_200.h"
#include "OAIInline_response_200_1.h"
#include "OAIInline_response_200_2.h"
#include "OAIInline_response_200_3.h"
#include "OAIInline_response_200_4.h"
#include "OAIInline_response_200_5.h"
#include "OAIInline_response_404.h"
#include "OAIInline_response_404_1.h"
#include "OAIObject.h"

#include "sqlthread.h"

#include <QString>

namespace OpenAPI {

class OAIDefaultApiHandler : public QObject
{
    Q_OBJECT
    
public:
    OAIDefaultApiHandler();
    virtual ~OAIDefaultApiHandler();


public slots:
    virtual void doctorGet(qint32 office);
    virtual void doctorIdGet(qint32 id);
    virtual void loginGet(QString username, QString password);
    virtual void notificationsGet(QString tags, QString date);
    virtual void officeIdGet(qint32 id);
    virtual void userIdGet(QString id);
    virtual void userIdPost(QString id);

private:
    SqlThread thread;

};

}

#endif // OAI_OAIDefaultApiHandler_H
